# Generated by Django 5.0 on 2023-12-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGlob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='AGlob', max_length=100),
        ),
    ]
